# -*- coding: utf-8 -*-
"""w6-synthetic data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q5YiaPitllKLZUplgmieKvuo_C_qCE71
"""

import google.generativeai as genai

genai.configure(api_key="") # key applied when running the programme

LLM = "gemini-2.5-flash-lite"
model = genai.GenerativeModel(LLM)

with open("web_search_query.csv", "r", encoding="utf-8") as f:
    lines = f.readlines()
    i = 0
    for line in lines:
        if i <= 3 and i > 0:
          line = line.split(",")
          line = line[1].strip()
          misspellings = model.generate_content(f"read this query and generate 5 misspellings of error types including phonetic, omission, transposition and repetition: {line}. Only return pure JSON list avoiding any possible markdown formats of "'''JSON'''" for each and every query").text
          print(misspellings)
        i += 1